//@ui5-bundle project1/Component-preload.js
sap.ui.predefine("project1/Component", ["sap/ui/core/UIComponent","project1/model/models"],(e,t)=>{"use strict";return e.extend("project1.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
sap.ui.predefine("project1/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("project1.controller.App",{onInit(){}})});
sap.ui.predefine("project1/controller/View1.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(t,e){"use strict";return t.extend("project1.controller.View1",{_sLastSelectedPath:null,onInit:function(){var t={materials:[{Material:"MAT1001",Description:"Steel Bolt",Plant:"PL01",Batch:"B001",Bin:"BIN-A-01"},{Material:"MAT1002",Description:"Iron Rod",Plant:"PL02",Batch:"B002",Bin:"BIN-B-02"},{Material:"MAT1003",Description:"Copper Pipe",Plant:"PL03",Batch:"B003",Bin:"BIN-C-03"},{Material:"MAT1004",Description:"plastic Pipe",Plant:"PL04",Batch:"B004",Bin:"BIN-C-04"},{Material:"MAT1005",Description:"Gold Rod",Plant:"PL05",Batch:"B005",Bin:"BIN-C-05"}]};this.getView().setModel(new e(t));this.getView().setModel(new e({}),"detail")},onMaterialPress:function(t){var e=t.getSource();var i=e.getBindingContext().getPath();var a=this.byId("detailCard");if(this._sLastSelectedPath===i&&a.getVisible()){a.setVisible(false);this._sLastSelectedPath=null;return}var l=this.getView().getModel().getProperty(i);this.getView().getModel("detail").setData(l);a.setVisible(true);this._sLastSelectedPath=i}})});
sap.ui.predefine("project1/model/models", ["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
sap.ui.require.preload({
	"project1/i18n/i18n.properties":'# This is the resource bundle for project1\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=MV Material View\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=MV Material View',
	"project1/manifest.json":'{"_version":"1.85.0","sap.app":{"id":"project1","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""]},"applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.25.0","toolsId":"e4a859f8-ad4b-45d0-a507-fb77d9f4d822"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.148.1","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"project1.i18n.i18n","supportedLocales":[""]}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"project1.view","async":true,"viewPath":"project1.view"},"routes":[{"name":"RouteView1","pattern":":?query:","target":["TargetView1"]}],"targets":{"TargetView1":{"id":"View1","name":"View1"}}},"rootView":{"viewName":"project1.view.App","type":"XML","id":"App","async":true},"flexBundle":false}}',
	"project1/view/App.view.xml":'<mvc:View controllerName="project1.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"project1/view/View1.view.xml":'<mvc:View\n    controllerName="project1.controller.View1"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n    displayBlock="true"><Page title="🏭 Warehouse Bin Viewer" class="sapUiResponsiveContentPadding"><content><VBox class="headerBanner"><Title text="Material List" level="H2" class="headerTitle"/><Text text="Tap a material row to view its warehouse bin details" class="headerSubtitle"/></VBox><List\n                id="materialList"\n                items="{/materials}"\n                mode="None"\n                class="materialList"><items><ObjectListItem\n                        title="{Material} - {Description}"\n                        type="Active"\n                        press="onMaterialPress"\n                        class="materialListItem"><attributes><ObjectAttribute text="🏭 Plant: {Plant}"/><ObjectAttribute text="📦 Bin: {Bin}"/></attributes></ObjectListItem></items></List><VBox id="detailCard" visible="false" class="detailCard"><VBox class="detailCardHeader"><Title text="📦 Bin Detail" level="H2" class="detailTitle"/></VBox><ObjectHeader\n                    title="{detail>/Material}"\n                    class="detailObjectHeader"><attributes><ObjectAttribute title="📝 Description" text="{detail>/Description}"/><ObjectAttribute title="🏭 Plant Code" text="{detail>/Plant}"/><ObjectAttribute title="🔖 Batch Number" text="{detail>/Batch}"/><ObjectAttribute title="📍 Bin Location" text="{detail>/Bin}"/></attributes></ObjectHeader></VBox></content></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
